# Generated by Django 4.0 on 2022-06-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_custumer_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(default='this is a note', max_length=200),
        ),
    ]
